package com.sherry.houserent.service;

import com.sherry.houserent.domain.House;
import com.sherry.houserent.utility.Utility;

public class HouseService {
    private House[] houses;

    private int houseNums = 1; // record the numbers of houses currently in the system
    private int idCounter = 1; // record the id of the house

    public HouseService(int size) {
        houses = new House[size];
        houses[0] = new House(1, "jack", "112", "eiuhfieh", 20000, "Not Rent");
    }

    public boolean search(int findId) {
        int index = -1;
        for (int i = 0; i < houseNums; i++) {
            if(findId == houses[i].getId()) {
                index = i;
                break;
            }
        }
        if(index == -1) {
            System.out.println("The house with id " + findId + " does not exist");
            return false;
        } else {
            System.out.println(houses[index]);
            return true;
        }
    }
    public boolean add(House newHouse) {
        if (houseNums == houses.length) {
            System.out.println("The house list is full. Cannot add");
            return false;
        }
        houses[houseNums++] = newHouse;
        newHouse.setId(++idCounter);//update the id of the house
        return true;

    }

    public boolean delete(int delId) {
        int index = -1;
        for (int i = 0; i < houseNums; i++) {
            if(delId == houses[i].getId()) {
                index = i;
                break;
            }
        }
        
        if(index == -1) {
            System.out.println("The house with id " + delId + " does not exist");
            return false;
        }
        for (int i = index; i < houseNums -1; i++) {
            houses[i] = houses[i+1];
        }
        houses[houseNums-1] = null;
        houseNums--;
        return true;
    }

    public boolean revise(int reviseId){
        int index = -1;
        for (int i = 0; i < houseNums; i++) {
            if(reviseId == houses[i].getId()) {
                index = i;
                break;
            }
        }
        if(index == -1) {
            System.out.println("The house with id " + reviseId + " does not exist");
            return false;
        }
        System.out.println("Name: ");
        String name = Utility.readString(8, houses[index].getName());
        System.out.println("Phone: ");
        String phone = Utility.readString(12, houses[index].getPhone());
        System.out.println("Address: ");
        String address = Utility.readString(16, houses[index].getAddress());
        System.out.println("Rent: ");
        int rent = Utility.readInt();
        System.out.println("Status: ");
        String state = Utility.readString(8, houses[index].getState());
        // The id should be automatically generated by the system
        houses[index] = new House(reviseId, name, phone, address, rent, state);

    return true;
    }


    public House[] list() {
        return houses;
    }

    public House[] getHouses() {
        return houses;
    }

    public void setHouses(House[] houses) {
        this.houses = houses;
    }

    public int getHouseNums() {
        return houseNums;
    }

    public void setHouseNums(int houseNums) {
        this.houseNums = houseNums;
    }

    public int getIdCounter() {
        return idCounter;
    }

    public void setIdCounter(int idCounter) {
        this.idCounter = idCounter;
    }
}
